# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main, dev/*, debug/* ]
  pull_request:
    branches: [ main, dev/*, debug/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update
        # sudo apt install -y libxcb-xinerama0 xvfb x11-utils libxkbcommon-x11-0 libxkbcommon-x11-0 
        sudo apt-get install -y 'libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r ./ammp/requirements.txt
        pip install -r ./tests/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Lint according to PEP8
        flake8 . --count --max-complexity=10 --max-line-length=79 --statistics
    - name: Test with pytest
      env:
        QT_DEBUG_PLUGINS: 1
      run: |
        pytest -sv
